CREATE TABLE capacitor LIKE resistor;
INSERT INTO capacitor SELECT * FROM resistor;
CREATE TABLE connector LIKE resistor;
INSERT INTO connector SELECT * FROM resistor;
CREATE TABLE diode LIKE resistor;
INSERT INTO diode SELECT * FROM resistor;
CREATE TABLE inductor LIKE resistor;
INSERT INTO inductor SELECT * FROM resistor;
CREATE TABLE ic LIKE resistor;
INSERT INTO ic SELECT * FROM resistor;
CREATE TABLE oscillator LIKE resistor;
INSERT INTO oscillator SELECT * FROM resistor;
CREATE TABLE mechanical LIKE resistor;
INSERT INTO mechanical SELECT * FROM resistor;